[package]
name = "std-thread"
version = "0.1.0"
authors = ["hello2mao <hello2mao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
